# Site settings
title: CRAS (Canada)
header-img: img/home-bg.jpg
# email: crascanada@gmail.com
copyright_name: Chinese Research & Analytics Society (Canada)
description: "Chinese Research & Analytics Society (Canada) is a non-for-profit professional organization that serves as a community for Research & Analytics professionals originally from China and is also committed to bridge the information and insights gap about Canadian Chinese, one of the largest ethnic group in Canada. "
baseurl: ""
url: "https://CRASCanada.org"
logo: /img/logos/CRASC.png

linkedin_username: 22334010
weixin_username: MzU0NzA0NzMyNw==&scene=124#wechat_redirect
email_username:  crascanada@gmail.com

# Google Analytics
# To enable google analytics, uncomment below line with a valid Google Tracking ID
google_tracking_id: UA-101158973-1

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed, jekyll-sitemap]

excerpt_separator: "<!--more-->"
